# Generated by Django 5.2.1 on 2025-05-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_alter_newsarticle_link_alter_newsarticle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
