# Generated by Django 5.2.1 on 2025-05-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_newsarticle_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='source',
        ),
    ]
